### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by laszlof** [laszlof/js-contra#1]
I'd like to remove the dependency for jquery in this project. Seems like a good hacktoberfest objective!

Hack away!

**Comment by joshuafbarker** [comment]
Seems fun. I'm on it!

**Comment by joshuafbarker** [comment]
Everything is done except for the character movement animation.

https://github.com/joshuafbarker/js-contra/blob/bc1e5dfc7964a9795eb2207806989775eea7431d/javascripts/contra.js

Will finish up tomorrow!

**Comment by laszlof** [comment]
Nice. Thanks for the help :)

**Comment by joshuafbarker** [comment]
@laszlof Done, done and done.

**Comment by laszlof** [comment]
Merged. Thanks!
