### ISSUE TITLE
Create Grunt/Bower/etc script to automatic minification of JS

### ISSUE THREAD

**Issue by laszlof** [laszlof/js-contra#3]
Use an automation tool like bower or Grunt to automatically minify the javascript file. Sounds like another Hacktoberfest project! Have fun!

**Comment by joshuafbarker** [comment]
I can handle this one as well. Would Gulp work for you? Also, to add this part to the repo, I would need to add a package.json, and re-structure the project a bit to accommodate.

**Comment by laszlof** [comment]
Gulp is fine. Feel free to restructure however you choose.

**Comment by jChris85** [comment]
Would you like to have a grunt file too?

**Comment by laszlof** [comment]
@jChris85 Sure. Might as well support both options. Please collaborate with @joshuafbarker on project structure.

**Comment by jChris85** [comment]
@laszlof sure I will implement the grunt file similar to @joshuafbarker gulp file.

**Comment by laszlof** [comment]
Thanks guys! Both PR's have been merged.
